const productos = [
    {
        id: 1,
        productName: "Desodorante de ambiente",
        price: 550,
        quanty: 1,
        description: "aerosol desodorante de ambientes",
        img: "../media/aerosoles.jpg",
    },
    {
        id: 2,
        productName: "Escobillon virulana",
        price: 2000,
        quanty: 1,
        description: "cepillo mediano para barrido de pisos",
        img: "../media/Escobillon-interiores-virulana.webp",
    },
    {
        id: 3,
        productName: "Guantes de limpieza",
        price: 430,
        quanty: 1,
        description: "guantes de latex para limpieza",
        img: "../media/guantes.webp",
    }, 
    {
        id: 4,
        productName: "Lavandina",
        price: 640,
        quanty: 1,
        description: "bidón de 2L de lavandina de primera marca",
        img: "../media/lavandina-ayudin-1-litro-clasica.webp",
    },
    {
        id: 5,
        productName: "Papel higienico",
        price: 550,
        quanty: 1,
        description: "papel higiénico de 30m por 4 unidades",
        img: "/client/media/higienol-papel-higienico-80-mts-hs.jpg",
    }, 
    {
        id: 6,

        productName: "Perfumina para piso",
        price: 320,
        quanty: 1,
        description: "líquido limpiapisos con perfume",
        img: "/client/media/Poett.webp",
    }, 
    {
        id: 7,
        productName: "Trapo de piso",
        price: 270,
        quanty: 1,
        description: "trapo de piso calidad intermedia",
        img: "/client/media/trapo-de-piso.webp",
    }, 
     
]       
