const productos = [
    {
        id: 1,
        productName: "desodorante de ambientes",
        price: 550,
        quanty: 1,
        description: "aerosol desodorante de ambientes",
        img: "client\media\desodorantedeambiente.jpg",
    },
    {
        id: 2,
        productName: "escobillon",
        price: 2000,
        quanty: 1,
        description: "cepillo mediano para barrido de pisos",
        img: "client\media\esscobillon.jpg",
    },
    {
        id: 3,
        productName: "guantes de limpieza",
        price: 430,
        quanty: 1,
        description: "guantes de latex para limpieza",
        img: "client\media\guantesdelimpieza.png",
    }, 
    {
        id: 4,
        productName: "lavandina",
        price: 640,
        quanty: 1,
        description: "bidón de 2L de lavandina de primera marca",
        img: "client\media\lavandina.jpg",
    },
    {
        id: 5,
        productName: "papel de baño",
        price: 550,
        quanty: 1,
        description: "papel higiénico de 30m por 4 unidades",
        img: "client\media\papelhigienico.jpg",

    }, 
    {
        id: 6,
        productName: "perfume para piso",
        price: 320,
        quanty: 1,
        description: "líquido limpiapisos con perfume",
        img: "client\media\perfumeparapiso.jpg",
    }, 
    {
        id: 7,
        productName: "trapo de piso",
        price: 270,
        quanty: 1,
        description: "trapo de piso calidad intermedia",
        img: "client\media\trapodepiso.jpeg",
    }, 
     
]       
